name: EC2 Deployment
on: 
  push:
    branches: 
      - deploy
      - ci-cd

  pull_request:
    branches: 
      - deploy
jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checks out this branch
        uses: actions/checkout@v3
      - name: whoisthis
        run:
          ifconfig

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 54.255.120.79
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
      - name: Trigger deployment
        run: 
            |
          echo "${{secrets.SSH_KEY}}"
          pem_to_ec2_full_path="$HOME/ssh.pem"
          echo "${{secrets.SSH_KEY}}" > $pem_to_ec2_full_path
          ls $pem_to_ec2_full_path
          deploy_hooks_dir=./dev-hooks/deployment-hooks
          cd $deploy_hooks_dir
          sudo ./trigger-deploy.sh $pem_to_ec2_full_path ${{secrets.EC2_IP}} ${GITHUB_SHA} ./deployec2gomoonbe.sh
        
