name: EC2 Deployment
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Prepare configuration from Github Secrets
        run: echo "${{ secrets.MYCONFIG }}"
      - name: run pre commit hook
        run: ./githooks/pre-commit
